In [56]:
import pandas as pd

In [57]:
geoplacesdata = pd.read_csv('dataset/geoplaces2.csv')
parkingdata = pd.read_csv('dataset/chefmozparking.csv')
cuisinedat = pd.read_csv('dataset/chefmozcuisine.csv')

In [58]:
geoplacesdata.head()

,placeID,latitude,longitude,the_geom_meter,name,address,city,state,country,fax,...,alcohol,smoking_area,dress_code,accessibility,price,url,Rambience,franchise,area,other_services
0,134999,18.915421,-99.184871,0101000020957F000088568DE356715AC138C0A525FC46...,Kiku Cuernavaca,Revolucion,Cuernavaca,Morelos,Mexico,?,...,No_Alcohol_Served,none,informal,no_accessibility,medium,kikucuernavaca.com.mx,familiar,f,closed,none
1,132825,22.147392,-100.983092,0101000020957F00001AD016568C4858C1243261274BA5...,puesto de tacos,esquina santos degollado y leon guzman,s.l.p.,s.l.p.,mexico,?,...,No_Alcohol_Served,none,informal,completely,low,?,familiar,f,open,none
2,135106,22.149709,-100.976093,0101000020957F0000649D6F21634858C119AE9BF528A3...,El Rinc�n de San Francisco,Universidad 169,San Luis Potosi,San Luis Potosi,Mexico,?,...,Wine-Beer,only at bar,informal,partially,medium,?,familiar,f,open,none
3,132667,23.752697,-99.163359,0101000020957F00005D67BCDDED8157C1222A2DC8D84D...,little pizza Emilio Portes Gil,calle emilio portes gil,victoria,tamaulipas,?,?,...,No_Alcohol_Served,none,informal,completely,low,?,familiar,t,closed,none
4,132613,23.752903,-99.165076,0101000020957F00008EBA2D06DC8157C194E03B7B504E...,carnitas_mata,lic. Emilio portes gil,victoria,Tamaulipas,Mexico,?,...,No_Alcohol_Served,permitted,informal,completely,medium,?,familiar,t,closed,none

In [59]:
geoplacesdata.info()

<class 'pandas.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   placeID         130 non-null    int64
 1   latitude        130 non-null    float64
 2   longitude       130 non-null    float64
 3   the_geom_meter  130 non-null    str
 4   name            130 non-null    str
 5   address         130 non-null    str
 6   city            130 non-null    str
 7   state           130 non-null    str
 8   country         130 non-null    str
 9   fax             130 non-null    str
 10  zip             130 non-null    str
 11  alcohol         130 non-null    str
 12  smoking_area    130 non-null    str
 13  dress_code      130 non-null    str
 14  accessibility   130 non-null    str
 15  price           130 non-null    str
 16  url             130 non-null    str
 17  Rambience       130 non-null    str
 18  franchise       130 non-null    str
 19  area            130 non-null    str
 20  other_services  130 non-null    str
dtypes: float64(2), int64(1), str(18)
memory usage: 21.5 KB

In [ ]:
#Dropping columns that wouldn't really affect ratings
geoplacesdata = geoplacesdata.drop(columns=['other_services','url','zip','fax','the_geom_meter'])

In [61]:
geoplacesdata.head()

,placeID,latitude,longitude,name,address,city,state,country,alcohol,smoking_area,dress_code,accessibility,price,Rambience,franchise,area
0,134999,18.915421,-99.184871,Kiku Cuernavaca,Revolucion,Cuernavaca,Morelos,Mexico,No_Alcohol_Served,none,informal,no_accessibility,medium,familiar,f,closed
1,132825,22.147392,-100.983092,puesto de tacos,esquina santos degollado y leon guzman,s.l.p.,s.l.p.,mexico,No_Alcohol_Served,none,informal,completely,low,familiar,f,open
2,135106,22.149709,-100.976093,El Rinc�n de San Francisco,Universidad 169,San Luis Potosi,San Luis Potosi,Mexico,Wine-Beer,only at bar,informal,partially,medium,familiar,f,open
3,132667,23.752697,-99.163359,little pizza Emilio Portes Gil,calle emilio portes gil,victoria,tamaulipas,?,No_Alcohol_Served,none,informal,completely,low,familiar,t,closed
4,132613,23.752903,-99.165076,carnitas_mata,lic. Emilio portes gil,victoria,Tamaulipas,Mexico,No_Alcohol_Served,permitted,informal,completely,medium,familiar,t,closed

In [62]:
geoplacesdata.info()

<class 'pandas.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   placeID        130 non-null    int64
 1   latitude       130 non-null    float64
 2   longitude      130 non-null    float64
 3   name           130 non-null    str
 4   address        130 non-null    str
 5   city           130 non-null    str
 6   state          130 non-null    str
 7   country        130 non-null    str
 8   alcohol        130 non-null    str
 9   smoking_area   130 non-null    str
 10  dress_code     130 non-null    str
 11  accessibility  130 non-null    str
 12  price          130 non-null    str
 13  Rambience      130 non-null    str
 14  franchise      130 non-null    str
 15  area           130 non-null    str
dtypes: float64(2), int64(1), str(13)
memory usage: 16.4 KB

In [63]:
# parkingdata_agg = (
#     parkingdata
#     .groupby('placeID')['parking_lot']
#     .agg(lambda x: list(x.dropna().unique()))
#     .reset_index()
# )

cuisinedat_agg = (
    cuisinedat
    .groupby('placeID')['Rcuisine']
    .agg(lambda x: list(x.dropna().unique()))
    .reset_index()
)

In [ ]:
geoplacesdata = pd.merge(geoplacesdata,parkingdata, on='placeID', how='left')
geoplacesdata = pd.merge(geoplacesdata, cuisinedat_agg, on='placeID', how='left')
geoplacesdata['placeID'] = geoplacesdata['placeID'].astype(str)

In [65]:
geoplacesdata.info()

<class 'pandas.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   placeID        130 non-null    int64
 1   latitude       130 non-null    float64
 2   longitude      130 non-null    float64
 3   name           130 non-null    str
 4   address        130 non-null    str
 5   city           130 non-null    str
 6   state          130 non-null    str
 7   country        130 non-null    str
 8   alcohol        130 non-null    str
 9   smoking_area   130 non-null    str
 10  dress_code     130 non-null    str
 11  accessibility  130 non-null    str
 12  price          130 non-null    str
 13  Rambience      130 non-null    str
 14  franchise      130 non-null    str
 15  area           130 non-null    str
 16  parking_lot    130 non-null    str
 17  Rcuisine       95 non-null     object
dtypes: float64(2), int64(1), object(1), str(14)
memory usage: 18.4+ KB

In [66]:
# Replacing ? with null
import numpy as np


total_data = geoplacesdata.copy()


total_data = total_data.replace('?', np.nan)
total_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   placeID        130 non-null    int64
 1   latitude       130 non-null    float64
 2   longitude      130 non-null    float64
 3   name           130 non-null    str
 4   address        103 non-null    str
 5   city           112 non-null    str
 6   state          112 non-null    str
 7   country        102 non-null    str
 8   alcohol        130 non-null    str
 9   smoking_area   130 non-null    str
 10  dress_code     130 non-null    str
 11  accessibility  130 non-null    str
 12  price          130 non-null    str
 13  Rambience      130 non-null    str
 14  franchise      130 non-null    str
 15  area           130 non-null    str
 16  parking_lot    130 non-null    str
 17  Rcuisine       95 non-null     object
dtypes: float64(2), int64(1), object(1), str(14)
memory usage: 18.4+ KB

In [67]:
# joining name adress etc to create single column
cols = ['name','address','city','state','country']
total_data['final_name'] = total_data[cols].fillna('').agg(', '.join, axis=1)

### List of nomial vars (cuisine) column embedding

In [68]:
# For cuisine - list column
#Could try with MultiLabelEncoder

from sklearn.preprocessing import LabelEncoder
# print(total_data['Rcuisine'])
total_data['Rcuisine'] = total_data['Rcuisine'].apply(lambda d: d if isinstance(d, list) else [])

all_cuisines = sorted({c for row in total_data['Rcuisine'] for c in row})

cuisine_le = LabelEncoder()
cuisine_le.fit(all_cuisines)

total_data['cuisine_ids'] = total_data['Rcuisine'].apply(
    lambda x: cuisine_le.transform(x).tolist()
)# list of cuisine ids now, instead of list of cuisines

num_cuisines = len(cuisine_le.classes_)

In [69]:
# nn layer for encoding the cuisine ids list in each row
import torch
import torch.nn as nn

class CuisineEncoder(nn.Module):
    def __init__(self, num_cuisines, emb_dim):
        super().__init__()
        self.embedding = nn.Embedding(num_cuisines, emb_dim)

    def forward(self, cuisine_ids):
        """
        cuisine_ids: List[int] or 1D tensor
        """
        cuisine_ids = torch.tensor(cuisine_ids, dtype=torch.long)
        emb = self.embedding(cuisine_ids)      # (num_cuisines_for_item, emb_dim)
        return emb.mean(dim=0) 
    
#to use
# in init of main model - self.cuisine_encoder = CuisineEncoder(num_cuisines, emb_dim)
# forward pass - cuisine_vec = self.cuisine_encoder(cuisine_ids)

# Ordinal vars embedding

In [ ]:
price_map = {
    'low': 0,
    'medium': 1,
    'high': 2
}

total_data['price_ord'] = total_data['price'].map(price_map)
total_data['price_ord'] = total_data['price_ord'] / 3.0

In [ ]:
dress_map = {
    'informal': 0,
    'casual': 1,
    'formal': 2
}

total_data['dress_ord'] = total_data['dress_code'].map(dress_map)
total_data['dress_ord'] = total_data['dress_ord'] / 3.0

In [ ]:
accessibility_map = {
    'no_accessibility' : 0,
    'partially':1,
    'completely':2
}

total_data['accessibility_ord'] = total_data['accessibility'].map(accessibility_map)
total_data['accessibility_ord'] = total_data['accessibility_ord'] / 3.0

In [ ]:
alcohol_map = {
    'No_Alcohol_Served':0,
    'Wine-Beer':1,
    'Full_Bar':2,
}

total_data['alcohol_ord'] = total_data['alcohol'].map(alcohol_map)

total_data['alcohol_ord'] = total_data['alcohol_ord'] / 3.0

### Binary Encoding

In [74]:

total_data['is_franchise'] = (total_data['franchise'] == 't').astype(int)
total_data['is_open'] = (total_data['area'] == 'open').astype(int)

### Nominal encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder

def label_encode(col):
    le = LabelEncoder()
    total_data[col + '_id'] = le.fit_transform(total_data[col].astype(str))
    return le

smoking_le = label_encode('smoking_area')
ambience_le = label_encode('Rambience')
parking_le = label_encode('parking_lot')

#in model self.smoking_emb = nn.Embedding(df['smoking_area_id'].nunique(), 4)
# self.smoking_emb = nn.Embedding(df['smoking_area_id'].nunique(), 4)

### Adding ratings

In [ ]:
# Created merged df with the review for the places
ratings_data = pd.read_csv('dataset/rating_final.csv')
ratings_data['placeID'] = ratings_data['placeID'].astype(str)
ratings_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1161 entries, 0 to 1160
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   userID          1161 non-null   str
 1   placeID         1161 non-null   int64
 2   rating          1161 non-null   int64
 3   food_rating     1161 non-null   int64
 4   service_rating  1161 non-null   int64
dtypes: int64(4), str(1)
memory usage: 45.5 KB

In [77]:
rating_cols = ['rating', 'food_rating', 'service_rating']

place_stats = (
    ratings_data
    .groupby('placeID')[rating_cols]
    .agg(['count', 'min', 'max', 'mean'])
    .reset_index()
)

# flatten column names
place_stats.columns = [
    'placeID',
    'rating_count', 'rating_min', 'rating_max', 'rating_mean',
    'food_count', 'food_min', 'food_max', 'food_mean',
    'service_count', 'service_min', 'service_max', 'service_mean'
]

In [78]:
global_means = ratings_data[rating_cols].mean()

#bayesian smoothing
m = 10  # smoothing strength

for col in ['rating', 'food', 'service']:
    place_stats[f'{col}_bayes'] = (
        (place_stats[f'{col}_count'] * place_stats[f'{col}_mean'] +
         m * global_means[col if col=='rating' else f'{col}_rating'])
        / (place_stats[f'{col}_count'] + m)
    )


#Normalizing
rating_features = [
    c for c in place_stats.columns
    if c.endswith(('min', 'max', 'mean', 'bayes'))
]

place_stats[rating_features] = place_stats[rating_features] / 5.0


count_cols = ['rating_count', 'food_count', 'service_count']

place_stats[count_cols] = np.log1p(place_stats[count_cols])

In [79]:
total_data = total_data.merge(place_stats, on='placeID', how='left')
total_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 44 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   placeID            130 non-null    int64
 1   latitude           130 non-null    float64
 2   longitude          130 non-null    float64
 3   name               130 non-null    str
 4   address            103 non-null    str
 5   city               112 non-null    str
 6   state              112 non-null    str
 7   country            102 non-null    str
 8   alcohol            130 non-null    str
 9   smoking_area       130 non-null    str
 10  dress_code         130 non-null    str
 11  accessibility      130 non-null    str
 12  price              130 non-null    str
 13  Rambience          130 non-null    str
 14  franchise          130 non-null    str
 15  area               130 non-null    str
 16  parking_lot        130 non-null    str
 17  Rcuisine           130 non-null    object
 18  final_name         130 non-null    str
 19  cuisine_ids        130 non-null    object
 20  price_ord          130 non-null    float64
 21  dress_ord          130 non-null    float64
 22  accessibility_ord  130 non-null    float64
 23  alcohol_ord        130 non-null    float64
 24  is_franchise       130 non-null    int64
 25  is_open            130 non-null    int64
 26  smoking_area_id    130 non-null    int64
 27  Rambience_id       130 non-null    int64
 28  parking_lot_id     130 non-null    int64
 29  rating_count       130 non-null    float64
 30  rating_min         130 non-null    float64
 31  rating_max         130 non-null    float64
 32  rating_mean        130 non-null    float64
 33  food_count         130 non-null    float64
 34  food_min           130 non-null    float64
 35  food_max           130 non-null    float64
 36  food_mean          130 non-null    float64
 37  service_count      130 non-null    float64
 38  service_min        130 non-null    float64
 39  service_max        130 non-null    float64
 40  service_mean       130 non-null    float64
 41  rating_bayes       130 non-null    float64
 42  food_bayes         130 non-null    float64
 43  service_bayes      130 non-null    float64
dtypes: float64(21), int64(6), object(2), str(15)
memory usage: 44.8+ KB

## USER

In [ ]:
userprofile_data = pd.read_csv('dataset/userprofile.csv')
usercuisine_data= pd.read_csv('dataset/usercuisine.csv')

In [81]:
usercuisinedat_agg = (
    usercuisine_data
    .groupby('userID')['Rcuisine']
    .agg(lambda x: list(x.dropna().unique()))
    .reset_index()
)
userprofile_data = pd.merge(userprofile_data, usercuisinedat_agg, on='userID', how='left')

In [82]:
userprofile_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 138 entries, 0 to 137
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   userID            138 non-null    str
 1   latitude          138 non-null    float64
 2   longitude         138 non-null    float64
 3   smoker            138 non-null    str
 4   drink_level       138 non-null    str
 5   dress_preference  138 non-null    str
 6   ambience          138 non-null    str
 7   transport         138 non-null    str
 8   marital_status    138 non-null    str
 9   hijos             138 non-null    str
 10  birth_year        138 non-null    int64
 11  interest          138 non-null    str
 12  personality       138 non-null    str
 13  religion          138 non-null    str
 14  activity          138 non-null    str
 15  color             138 non-null    str
 16  weight            138 non-null    int64
 17  budget            138 non-null    str
 18  height            138 non-null    float64
 19  Rcuisine          138 non-null    object
dtypes: float64(3), int64(2), object(1), str(14)
memory usage: 21.7+ KB

In [83]:
userprofile_data['age'] = 2026 - userprofile_data['birth_year']
userprofile_data = userprofile_data.replace('?', np.nan)

for col in userprofile_data.columns:
    if col=='Rcuisine':
        continue
    mode = userprofile_data[col].mode()[0]
    userprofile_data[col] = userprofile_data[col].fillna(mode)

### List of nominal vars

In [84]:
# For cuisine - list column
#Could try with MultiLabelEncoder

from sklearn.preprocessing import LabelEncoder
# print(total_data['Rcuisine'])
userprofile_data['Rcuisine'] = userprofile_data['Rcuisine'].apply(lambda d: d if isinstance(d, list) else [])

all_cuisines = sorted({c for row in userprofile_data['Rcuisine'] for c in row})

usercuisine_le = LabelEncoder()
usercuisine_le.fit(all_cuisines)

userprofile_data['cuisine_ids'] = userprofile_data['Rcuisine'].apply(
    lambda x: usercuisine_le.transform(x).tolist()
)# list of cuisine ids now, instead of list of cuisines

num_usercuisines = len(usercuisine_le.classes_)

In [85]:
# nn layer for encoding the cuisine ids list in each row
import torch
import torch.nn as nn

class UserCuisineEncoder(nn.Module):
    def __init__(self, num_cuisines, emb_dim):
        super().__init__()
        self.embedding = nn.Embedding(num_cuisines, emb_dim)

    def forward(self, cuisine_ids):
        """
        cuisine_ids: List[int] or 1D tensor
        """
        cuisine_ids = torch.tensor(cuisine_ids, dtype=torch.long)
        emb = self.embedding(cuisine_ids)      # (num_cuisines_for_item, emb_dim)
        return emb.mean(dim=0) 
    
#to use
# in init of main model - self.cuisine_encoder = CuisineEncoder(num_cuisines, emb_dim)
# forward pass - cuisine_vec = self.cuisine_encoder(cuisine_ids)

### Ordinal vars

In [ ]:
drinklevel_map = {
    'abstemious': 0,
    'social drinker': 1,
    'casual drinker': 2
}

userprofile_data['drink_level_ord'] = userprofile_data['drink_level'].map(drinklevel_map)
userprofile_data['drink_level_ord'] = userprofile_data['drink_level_ord'] / 3.0

In [ ]:
budget_map = {
    'low': 0,
    'medium': 1,
    'high': 2
}

userprofile_data['budget_ord'] = userprofile_data['budget'].map(budget_map)
userprofile_data['budget_ord'] = userprofile_data['budget_ord'] / 3.0

### Boolean vars

In [88]:
userprofile_data['is_smoker'] = (userprofile_data['smoker'] == 'true').astype(int)

### Nominal vars

In [89]:
from sklearn.preprocessing import LabelEncoder

def label_encode(col):
    le = LabelEncoder()
    
    userprofile_data[col + '_id'] = le.fit_transform(userprofile_data[col].astype(str))
    return le

dress_preference_le = label_encode('dress_preference')
userambience_le = label_encode('ambience')
transport_le = label_encode('transport')
marital_le = label_encode('marital_status')
hijos_le = label_encode('hijos')
interest_le = label_encode('interest')
personality_le = label_encode('personality')
religion_le = label_encode('religion')
activity_le = label_encode('activity')

#in model self.smoking_emb = nn.Embedding(df['smoking_area_id'].nunique(), 4)
# self.smoking_emb = nn.Embedding(df['smoking_area_id'].nunique(), 4)

### Normalizing numeric vars

##### Z-score normalization

In [ ]:
from sklearn.preprocessing import StandardScaler

heightscaler = StandardScaler()
weightscaler = StandardScaler()
agescaler = StandardScaler()

userprofile_data['height_norm'] = heightscaler.fit_transform(
    userprofile_data[['height']]
)

userprofile_data['weight_norm'] = weightscaler.fit_transform(
    userprofile_data[['weight']]
)

userprofile_data['age_norm'] = agescaler.fit_transform(
    userprofile_data[['age']]
)

In [91]:
userprofile_data.head()

,userID,latitude,longitude,smoker,drink_level,dress_preference,ambience,transport,marital_status,hijos,...,transport_id,marital_status_id,hijos_id,interest_id,personality_id,religion_id,activity_id,height_norm,weight_norm,age_norm
0,U1001,22.139997,-100.978803,false,abstemious,informal,family,on foot,single,independent,...,1,1,1,4,3,4,1,0.788189,0.240816,-0.294278
1,U1002,22.150087,-100.983325,false,abstemious,informal,family,public,single,independent,...,2,1,1,3,2,0,1,1.557426,-1.449964,-0.362761
2,U1003,22.119847,-100.946527,false,social drinker,formal,family,public,single,independent,...,2,1,1,1,1,0,1,0.172800,-0.283909,-0.294278
3,U1004,18.867000,-99.183000,false,abstemious,informal,family,public,single,independent,...,2,1,1,4,1,4,0,-1.057980,-1.216753,3.061388
4,U1005,22.183477,-100.959891,false,abstemious,no preference,family,public,single,independent,...,2,1,1,1,3,0,1,0.172800,0.007605,-0.499727

In [92]:
userprofile_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 138 entries, 0 to 137
Data columns (total 37 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   userID               138 non-null    str
 1   latitude             138 non-null    float64
 2   longitude            138 non-null    float64
 3   smoker               138 non-null    str
 4   drink_level          138 non-null    str
 5   dress_preference     138 non-null    str
 6   ambience             138 non-null    str
 7   transport            138 non-null    str
 8   marital_status       138 non-null    str
 9   hijos                138 non-null    str
 10  birth_year           138 non-null    int64
 11  interest             138 non-null    str
 12  personality          138 non-null    str
 13  religion             138 non-null    str
 14  activity             138 non-null    str
 15  color                138 non-null    str
 16  weight               138 non-null    int64
 17  budget               138 non-null    str
 18  height               138 non-null    float64
 19  Rcuisine             138 non-null    object
 20  age                  138 non-null    int64
 21  cuisine_ids          138 non-null    object
 22  drink_level_ord      138 non-null    float64
 23  budget_ord           138 non-null    float64
 24  is_smoker            138 non-null    int64
 25  dress_preference_id  138 non-null    int64
 26  ambience_id          138 non-null    int64
 27  transport_id         138 non-null    int64
 28  marital_status_id    138 non-null    int64
 29  hijos_id             138 non-null    int64
 30  interest_id          138 non-null    int64
 31  personality_id       138 non-null    int64
 32  religion_id          138 non-null    int64
 33  activity_id          138 non-null    int64
 34  height_norm          138 non-null    float64
 35  weight_norm          138 non-null    float64
 36  age_norm             138 non-null    float64
dtypes: float64(8), int64(13), object(2), str(14)
memory usage: 40.0+ KB

# BERT Embeddings

In [93]:
from sentence_transformers import SentenceTransformer

# Load a production-ready BERT model
model = SentenceTransformer('./models/all-MiniLM-L6-v2')

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [94]:
total_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 44 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   placeID            130 non-null    int64
 1   latitude           130 non-null    float64
 2   longitude          130 non-null    float64
 3   name               130 non-null    str
 4   address            103 non-null    str
 5   city               112 non-null    str
 6   state              112 non-null    str
 7   country            102 non-null    str
 8   alcohol            130 non-null    str
 9   smoking_area       130 non-null    str
 10  dress_code         130 non-null    str
 11  accessibility      130 non-null    str
 12  price              130 non-null    str
 13  Rambience          130 non-null    str
 14  franchise          130 non-null    str
 15  area               130 non-null    str
 16  parking_lot        130 non-null    str
 17  Rcuisine           130 non-null    object
 18  final_name         130 non-null    str
 19  cuisine_ids        130 non-null    object
 20  price_ord          130 non-null    float64
 21  dress_ord          130 non-null    float64
 22  accessibility_ord  130 non-null    float64
 23  alcohol_ord        130 non-null    float64
 24  is_franchise       130 non-null    int64
 25  is_open            130 non-null    int64
 26  smoking_area_id    130 non-null    int64
 27  Rambience_id       130 non-null    int64
 28  parking_lot_id     130 non-null    int64
 29  rating_count       130 non-null    float64
 30  rating_min         130 non-null    float64
 31  rating_max         130 non-null    float64
 32  rating_mean        130 non-null    float64
 33  food_count         130 non-null    float64
 34  food_min           130 non-null    float64
 35  food_max           130 non-null    float64
 36  food_mean          130 non-null    float64
 37  service_count      130 non-null    float64
 38  service_min        130 non-null    float64
 39  service_max        130 non-null    float64
 40  service_mean       130 non-null    float64
 41  rating_bayes       130 non-null    float64
 42  food_bayes         130 non-null    float64
 43  service_bayes      130 non-null    float64
dtypes: float64(21), int64(6), object(2), str(15)
memory usage: 44.8+ KB

In [ ]:
def safe(x):
    return "" if pd.isna(x) else str(x)

def build_text_groups(row):
    location = (
        f"{safe(row['name'])}. Located at "
        f"{safe(row['address'])}, {safe(row['city'])}, "
        f"{safe(row['state'])}, {safe(row['country'])}."
    )

    attributes = (
        f"Alcohol: {row['alcohol']}. "
        f"Smoking: {row['smoking_area']}. "
        f"Dress code: {row['dress_code']}. "
        f"Accessibility: {row['accessibility']}. "
        f"Price range: {row['price']}. "
        f"Ambience: {row['Rambience']}."
    )

    business = (
        f"Franchise: {row['franchise']}. "
        f"Area: {row['area']}. "
        f"Parking: {row['parking_lot']}."
    )

    cuisines = row['Rcuisine']
    cuisine = (
        "Cuisines: " + ", ".join(cuisines)
        if isinstance(cuisines, list) else "Cuisines:"
    )

    return location, attributes, business, cuisine

In [96]:
import numpy as np

final_bert_embs = []

for _, row in total_data.iterrows():
    loc, attr, biz, cui = build_text_groups(row)

    loc_e = model.encode(loc, normalize_embeddings=True)
    attr_e = model.encode(attr, normalize_embeddings=True)
    biz_e = model.encode(biz, normalize_embeddings=True)
    cui_e = model.encode(cui, normalize_embeddings=True)

    final_emb = np.concatenate(
        [loc_e, attr_e, biz_e, cui_e]
    )  # shape: (1536,)

    final_bert_embs.append(final_emb)

total_data['bert_embedding'] = final_bert_embs

In [97]:
total_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 45 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   placeID            130 non-null    int64
 1   latitude           130 non-null    float64
 2   longitude          130 non-null    float64
 3   name               130 non-null    str
 4   address            103 non-null    str
 5   city               112 non-null    str
 6   state              112 non-null    str
 7   country            102 non-null    str
 8   alcohol            130 non-null    str
 9   smoking_area       130 non-null    str
 10  dress_code         130 non-null    str
 11  accessibility      130 non-null    str
 12  price              130 non-null    str
 13  Rambience          130 non-null    str
 14  franchise          130 non-null    str
 15  area               130 non-null    str
 16  parking_lot        130 non-null    str
 17  Rcuisine           130 non-null    object
 18  final_name         130 non-null    str
 19  cuisine_ids        130 non-null    object
 20  price_ord          130 non-null    float64
 21  dress_ord          130 non-null    float64
 22  accessibility_ord  130 non-null    float64
 23  alcohol_ord        130 non-null    float64
 24  is_franchise       130 non-null    int64
 25  is_open            130 non-null    int64
 26  smoking_area_id    130 non-null    int64
 27  Rambience_id       130 non-null    int64
 28  parking_lot_id     130 non-null    int64
 29  rating_count       130 non-null    float64
 30  rating_min         130 non-null    float64
 31  rating_max         130 non-null    float64
 32  rating_mean        130 non-null    float64
 33  food_count         130 non-null    float64
 34  food_min           130 non-null    float64
 35  food_max           130 non-null    float64
 36  food_mean          130 non-null    float64
 37  service_count      130 non-null    float64
 38  service_min        130 non-null    float64
 39  service_max        130 non-null    float64
 40  service_mean       130 non-null    float64
 41  rating_bayes       130 non-null    float64
 42  food_bayes         130 non-null    float64
 43  service_bayes      130 non-null    float64
 44  bert_embedding     130 non-null    object
dtypes: float64(21), int64(6), object(3), str(15)
memory usage: 45.8+ KB

In [ ]:
def build_user_text_groups(row):
    lifestyle = " ".join(filter(None, [
        f"Smoker : {row['smoker']},",
        f"Drink level : {row['drink_level']},",
        f"Transport : {row['transport']},",
        f"Activity : {row['activity']},",
    ]))

    social = " ".join(filter(None, [
        f"Marital status : {row['marital_status']},",
        f"Hijos : {row['hijos']},",
        f"Personality : {row['personality']},",
        f"Interest : {row['interest']},",
        f"Religion : {row['religion']},",
    ]))

    preference = " ".join(filter(None, [
        f"Dress pref : {row['dress_preference']},",
        f"Ambience : {row['ambience']},",
        f"Budget : {row['budget']},",
    ]))

    cuisine = " ".join(row['Rcuisine']) if isinstance(row['Rcuisine'], list) else ""
    cuisine = f"Cuisine : {cuisine}"

    return lifestyle, social, preference, cuisine

In [99]:
final_bert_userembs = []

for _, row in userprofile_data.iterrows():
    life, soci, pref, cuis = build_user_text_groups(row)

    life_e = model.encode(life, normalize_embeddings=True)
    soci_e = model.encode(soci, normalize_embeddings=True)
    pref_e = model.encode(pref, normalize_embeddings=True)
    cuis_e = model.encode(cuis, normalize_embeddings=True)

    final_emb = np.concatenate(
        [life_e, soci_e, pref_e, cuis_e]
    )  # shape: (1536,)

    final_bert_userembs.append(final_emb)

userprofile_data['bert_embedding'] = final_bert_userembs

In [100]:
userprofile_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 138 entries, 0 to 137
Data columns (total 38 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   userID               138 non-null    str
 1   latitude             138 non-null    float64
 2   longitude            138 non-null    float64
 3   smoker               138 non-null    str
 4   drink_level          138 non-null    str
 5   dress_preference     138 non-null    str
 6   ambience             138 non-null    str
 7   transport            138 non-null    str
 8   marital_status       138 non-null    str
 9   hijos                138 non-null    str
 10  birth_year           138 non-null    int64
 11  interest             138 non-null    str
 12  personality          138 non-null    str
 13  religion             138 non-null    str
 14  activity             138 non-null    str
 15  color                138 non-null    str
 16  weight               138 non-null    int64
 17  budget               138 non-null    str
 18  height               138 non-null    float64
 19  Rcuisine             138 non-null    object
 20  age                  138 non-null    int64
 21  cuisine_ids          138 non-null    object
 22  drink_level_ord      138 non-null    float64
 23  budget_ord           138 non-null    float64
 24  is_smoker            138 non-null    int64
 25  dress_preference_id  138 non-null    int64
 26  ambience_id          138 non-null    int64
 27  transport_id         138 non-null    int64
 28  marital_status_id    138 non-null    int64
 29  hijos_id             138 non-null    int64
 30  interest_id          138 non-null    int64
 31  personality_id       138 non-null    int64
 32  religion_id          138 non-null    int64
 33  activity_id          138 non-null    int64
 34  height_norm          138 non-null    float64
 35  weight_norm          138 non-null    float64
 36  age_norm             138 non-null    float64
 37  bert_embedding       138 non-null    object
dtypes: float64(8), int64(13), object(3), str(14)
memory usage: 41.1+ KB

## Saving the setup data to db

In [ ]:

import psycopg2
import numpy as np

conn = psycopg2.connect(database='reco_db', user='reco_user',password='reco_pass')

cur = conn.cursor()

insert_sql = """
INSERT INTO user_profiles (
    userID, latitude, longitude,
    smoker, drink_level, budget, dress_preference, ambience, transport, marital_status, hijos, birth_year, interest, personality, religion, activity, color, weight, height, age,
    rcuisine, cuisine_ids,
    drink_level_ord, budget_ord, is_smoker,
    dress_preference_id, ambience_id, transport_id,
    marital_status_id, hijos_id, interest_id,
    personality_id, religion_id, activity_id,
    height_norm, weight_norm, age_norm,
    bert_embedding
)
VALUES (
    %s,%s,%s,
    %s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,
    %s,%s,
    %s,%s,%s,
    %s,%s,%s,
    %s,%s,%s,
    %s,%s,%s,
    %s,%s,%s,
    %s
)
ON CONFLICT (userID) DO NOTHING
"""

for _, row in userprofile_data.iterrows():
    cur.execute(
        insert_sql,
        (
            row.userID,
            float(row.latitude),
            float(row.longitude),

           str(row.smoker),
           str(row.drink_level),
           str(row.budget),
           str(row.dress_preference),
           str(row.ambience),
           str(row.transport),
           str(row.marital_status),
           str(row.hijos),
           int(row.birth_year),
           str(row.interest),
           str(row.personality),
           str(row.religion),
           str(row.activity),
           str(row.color),
           float(row.weight),
           float(row.height),
           float(row.age),

           row.Rcuisine,
           row.cuisine_ids,
          
            float(row.drink_level_ord),
            float(row.budget_ord),
            int(row.is_smoker),

            int(row.dress_preference_id),
            int(row.ambience_id),
            int(row.transport_id),
            int(row.marital_status_id),
            int(row.hijos_id),
            int(row.interest_id),
            int(row.personality_id),
            int(row.religion_id),
            int(row.activity_id),

            float(row.height_norm),
            float(row.weight_norm),
            float(row.age_norm),

            row.bert_embedding.tolist()  # MUST be Python list
        )
    )

conn.commit()

In [102]:
## TO READ FROM DB 
# import pandas as pd

# df = pd.read_sql("SELECT * FROM user_profiles", conn)

# X_bert = np.vstack(df['bert_embedding'].values)  # (N, 1536)

In [ ]:
insert_sql = """
INSERT INTO places (
    placeID, latitude, longitude,
    
    name, address, city, state, country, alcohol, smoking_area, dress_code, accessibility, price, rambience, franchise, area, parking_lot,
    rcuisine, cuisine_ids,

    price_ord, dress_ord, accessibility_ord, alcohol_ord,
    is_franchise, is_open,

    smoking_area_id, rambience_id, parking_lot_id,

    rating_count, rating_min, rating_max, rating_mean, rating_bayes,
    food_count, food_min, food_max, food_mean, food_bayes,
    service_count, service_min, service_max, service_mean, service_bayes,

    bert_embedding
)
VALUES (
    %s,%s,%s,
    %s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,
    %s,%s,
    %s,%s,%s,%s,
    %s,%s,
    %s,%s,%s,
    %s,%s,%s,%s,%s,
    %s,%s,%s,%s,%s,
    %s,%s,%s,%s,%s,
    %s
)
ON CONFLICT (placeID) DO NOTHING
"""

for _, row in total_data.iterrows():
    cur.execute(
        insert_sql,
        (
            str(row.placeID),
            float(row.latitude),
            float(row.longitude),
            str(row['name']), str(row.address), str(row.city), str(row.state), str(row.country), str(row.alcohol), str(row.smoking_area), str(row.dress_code), str(row.accessibility), str(row.price), str(row.Rambience), str(row.franchise), str(row.area), str(row.parking_lot),
            row.Rcuisine,
            row.cuisine_ids,
            float(row.price_ord),
            float(row.dress_ord),
            float(row.accessibility_ord),
            float(row.alcohol_ord),

            int(row.is_franchise),
            int(row.is_open),

            int(row.smoking_area_id),
            int(row.Rambience_id),
            int(row.parking_lot_id),

            float(row.rating_count) if not np.isnan(row.rating_count) else None,
            float(row.rating_min)   if not np.isnan(row.rating_min) else None,
            float(row.rating_max)   if not np.isnan(row.rating_max) else None,
            float(row.rating_mean)  if not np.isnan(row.rating_mean) else None,
            float(row.rating_bayes) if not np.isnan(row.rating_bayes) else None,

            float(row.food_count) if not np.isnan(row.food_count) else None,
            float(row.food_min)   if not np.isnan(row.food_min) else None,
            float(row.food_max)   if not np.isnan(row.food_max) else None,
            float(row.food_mean)  if not np.isnan(row.food_mean) else None,
            float(row.food_bayes) if not np.isnan(row.food_bayes) else None,

            float(row.service_count) if not np.isnan(row.service_count) else None,
            float(row.service_min)   if not np.isnan(row.service_min) else None,
            float(row.service_max)   if not np.isnan(row.service_max) else None,
            float(row.service_mean)  if not np.isnan(row.service_mean) else None,
            float(row.service_bayes) if not np.isnan(row.service_bayes) else None,

            row.bert_embedding.tolist()  # REQUIRED
        )
    )

conn.commit()

## Saving scalers and encoders

In [ ]:
from joblib import dump
import os

os.makedirs("artifacts/users/scalers", exist_ok=True)

dump(heightscaler, "artifacts/users/scalers/height_scaler.joblib")
dump(weightscaler, "artifacts/users/scalers/weight_scaler.joblib")
dump(agescaler,   "artifacts/users/scalers/age_scaler.joblib")

['artifacts/users/scalers/age_scaler.joblib']

In [105]:
from joblib import dump

os.makedirs("artifacts/users/encoders/userencoders", exist_ok=True)

dump(dress_preference_le, "artifacts/users/encoders/userencoders/dress_preference_le.joblib")
dump(userambience_le, "artifacts/users/encoders/userencoders/userambience_le.joblib")
dump(transport_le,  "artifacts/users/encoders/userencoders/transport_le.joblib")
dump(marital_le,  "artifacts/users/encoders/userencoders/marital_le.joblib")
dump(hijos_le,  "artifacts/users/encoders/userencoders/hijos_le.joblib")
dump(interest_le,  "artifacts/users/encoders/userencoders/interest_le.joblib")
dump(personality_le,  "artifacts/users/encoders/userencoders/personality_le.joblib")
dump(religion_le,  "artifacts/users/encoders/userencoders/religion_le.joblib")
dump(activity_le,  "artifacts/users/encoders/userencoders/activity_le.joblib")
dump(usercuisine_le, "artifacts/users/encoders/userencoders/usercuisine_le.joblib")

['artifacts/users/encoders/userencoders/usercuisine_le.joblib']

In [106]:
os.makedirs("artifacts/users/encoders/placeencoders", exist_ok=True)

dump(smoking_le,  "artifacts/users/encoders/placeencoders/smoking_le.joblib")
dump(ambience_le,  "artifacts/users/encoders/placeencoders/ambience_le.joblib")
dump(parking_le,  "artifacts/users/encoders/placeencoders/parking_le.joblib")
dump(cuisine_le,  "artifacts/users/encoders/placeencoders/cuisine_le.joblib")

['artifacts/users/encoders/placeencoders/cuisine_le.joblib']

In [107]:
#To load
# from joblib import load
# height_scaler = load("artifacts/users/scalers/height_scaler.joblib")
# drink_encoder = load("artifacts/users/encoders/drink_level_encoder.joblib")